/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.softSource.manager.xml -i softsourcemanager.h -a softSourceManagerAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SOFTSOURCEMANAGERADAPTOR_H
#define SOFTSOURCEMANAGERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "softsourcemanager.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.softSource.manager.interface
 */
class InterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.softSource.manager.interface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.softSource.manager.interface\">\n"
"    <method name=\"addSource\">\n"
"      <arg direction=\"in\" type=\"av\" name=\"sourceInfo\"/>\n"
"    </method>\n"
"    <method name=\"deleteSource\">\n"
"      <arg direction=\"in\" type=\"av\" name=\"sourceInfo\"/>\n"
"    </method>\n"
"    <method name=\"setMainSource\">\n"
"      <arg direction=\"in\" type=\"av\" name=\"sourceFileName\"/>\n"
"    </method>\n"
"    <method name=\"updateSource\"/>\n"
"    <method name=\"changedSource\">\n"
"      <arg direction=\"in\" type=\"av\" name=\"sourceInfo\"/>\n"
"    </method>\n"
"    <method name=\"addExtensionSource\">\n"
"      <arg direction=\"in\" type=\"av\" name=\"sourceInfo\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    InterfaceAdaptor(QObject *parent);
    virtual ~InterfaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void addExtensionSource(const QVariantList &sourceInfo);
    void addSource(const QVariantList &sourceInfo);
    void changedSource(const QVariantList &sourceInfo);
    void deleteSource(const QVariantList &sourceInfo);
    void setMainSource(const QVariantList &sourceFileName);
    void updateSource();
Q_SIGNALS: // SIGNALS
};

#endif
