/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.softSource.manager.xml -i softsourcemanager.h -a softSourceManagerAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "softSourceManagerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class InterfaceAdaptor
 */

InterfaceAdaptor::InterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

InterfaceAdaptor::~InterfaceAdaptor()
{
    // destructor
}

void InterfaceAdaptor::addSource(const QVariantList &sourceInfo)
{
    // handle method call com.softSource.manager.interface.addSource
    QMetaObject::invokeMethod(parent(), "addSource", Q_ARG(QVariantList, sourceInfo));
}

void InterfaceAdaptor::deleteSource(const QVariantList &sourceInfo)
{
    // handle method call com.softSource.manager.interface.deleteSource
    QMetaObject::invokeMethod(parent(), "deleteSource", Q_ARG(QVariantList, sourceInfo));
}

void InterfaceAdaptor::setMainSource(const QVariantList &sourceFileName)
{
    // handle method call com.softSource.manager.interface.setMainSource
    QMetaObject::invokeMethod(parent(), "setMainSource", Q_ARG(QVariantList, sourceFileName));
}

void InterfaceAdaptor::updateSource()
{
    // handle method call com.softSource.manager.interface.updateSource
    QMetaObject::invokeMethod(parent(), "updateSource");
}

